
name: Update Code To Note

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'your-app-name'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.10'                     # set this to the python version to use (e.g. '3.6', '3.7', '3.8')

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            sudo su -
            git config --global user.email "gptkok@gmail.com"
            git config --global user.name "wsdo"
            git config --global --add safe.directory /home/wwwroot/code/auto-gpt-work
            git config --global --add safe.directory /home/wwwroot/code/lecture-notes
            sh /home/wwwroot/code/update-lecture-notes.sh

